language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t achajackson/react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true achajackson/react-app npm run test

#deply to AWS EBS after test pass with Travis
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-236638675154"
  bucket_path: "reactapp-app"
  on:
    branch: masters
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true


