#require sudo permission to use docker
sudo: required

#call the service you want to use
services:
  - docker

#do some things before you install
before_install: 
# tag the image since we wont be able to get the imageID
#in this automated process
  - docker build -t achajackson/react-app -f Dockerfile.dev .

#after pulling the code from git, travis will run testing
script: 
  - docker run achajackson/react-app npm run test -- --coverage

#tell travis what to do after a successful test
deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-1"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-236638675154"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY




